version: '3'
services:
  core:
    build: .
    depends_on:
      - db
    environment:
      NETWORK_PASSPHRASE: "Test SDF Network ; September 2015"
      DATABASE: "postgresql://dbname=core user=pg password=pazz host=db"
      KNOWN_PEERS: "core-testnet1.stellar.org,core-testnet2.stellar.org,core-testnet3.stellar.org"
      HISTORY: |
        {
          "h1": { "get": "curl -sf http://s3-eu-west-1.amazonaws.com/history.stellar.org/prd/core-testnet/core_testnet_001/{0} -o {1}" },
          "h2": { "get": "curl -sf http://s3-eu-west-1.amazonaws.com/history.stellar.org/prd/core-testnet/core_testnet_002/{0} -o {1}" },
          "h3": { "get": "curl -sf http://s3-eu-west-1.amazonaws.com/history.stellar.org/prd/core-testnet/core_testnet_003/{0} -o {1}" }
        }
      NODE_NAMES: GDKXE2OZMJIPOSLNA6N6F2BVCI3O777I2OOC4BV7VOYUEHYX7RTRYA7Y  sdf1,GCUCJTIYXSOXKBSNFGNFWW5MUQ54HKRPGJUTQFJ5RQXZXNOLNXYDHRAP  sdf2,GC2V2EFSXN6SQTWVYA5EPJPBWWIMSD2XQNKUOHGEKB535AQE2I6IXV2Z  sdf3
      UNSAFE_QUORUM: "true"
      QUORUM_SET: |
        [
          {
            "threshold_percent": 50,
            "validators": [
              "GDKXE2OZMJIPOSLNA6N6F2BVCI3O777I2OOC4BV7VOYUEHYX7RTRYA7Y",
              "GCUCJTIYXSOXKBSNFGNFWW5MUQ54HKRPGJUTQFJ5RQXZXNOLNXYDHRAP",
              "GC2V2EFSXN6SQTWVYA5EPJPBWWIMSD2XQNKUOHGEKB535AQE2I6IXV2Z"
            ]
          }
        ]
      GS_SERVICE_ACCOUNT_KEY: |
        {
          "type": "service_account",
          "project_id": "bloom-general",
          "private_key_id": "a2ec8ae3169de95638d90f61f8820e980a4ebd03",
          "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDPdVUkHAfuDP/Y\noHdST290DAoJd+jk1ZErvXwUJD1Yu9LaiahUFk1VagBo+wP3n/jBtctLTDbzOAgn\nwGfTeTo8gj9zvDacbNKB+CGfWjslZ7rBbUME4wX3VtkSZ9Hib4+e3Lstsdrfjxhw\nOLTK8fMmTxscPN8MAOYh0u6swDeeCm16LWFFbcC5uz10a1Xv2hfSwbvS4HuL95My\ndsP3J1TvEpYCRPuRqSeED2Iw2hPpb30N8TefPiepZLaqb3c8wwQ2HINuXWqOztGV\nyj1rLmmGnIiWk0DC26QWSgh9wCc+B5wFcitquDr3vM94tEKTTlIUXw+YogztxUlB\nZyFPIjolAgMBAAECggEACydYRgI5zOsnADsUXzkFGXyiN4MaYt82mF7uIlkWcURb\n4EMBaU/vpXV3Ay3ntzMDGUsQXIKC+82Z5qU6D80XO/SWu761QvC42qMAD8S2pFqw\n2EBrF4KrKfKh5hLt3lo4IwbkC19iEJ3tZu8tjTG37GnZX8nIBimwNcZU7bXB5723\n6OTHWzW1ScA7xwYnwMZK3c//eDS1WQ5g1rUiA2J7itFGp9tmuNiaTb+j4+8Dzy1O\nLg+LGXq5hRpgiKKUvWp6Ks+cmSjjfgjKl0algUSeVPYqRX4hb0ldX6Yhtdhq4s4O\nASVbsZwPiCmYMAy29DyULiIvP5Rf0Vg0FGhNQDV02wKBgQD7HSap5NiBA9wNclhE\nw/ZQVwbPJtNLQ0ZXKfge9aN6WeAdTCM3EdD0a4PXY9FDB5aBMnArqEf5ssbdhTdM\n2k//waXzmzJyqhtpqoBu+uMXBYyYY+8imjNHa8/Jr8hkBmGbL2MHvXZYHYKbEjpF\n/+UckYcRH4iMEzHSzep3MozGRwKBgQDTfrl3QpJhD+PMj5yCoJtU+KucMRs1Bg0d\nSzr8lxywYn9FFJRNb6e6UVQ92pdrjQO3IrCWetfh5/Kgb+/Pa7Jwb4nlB42WJEDb\nLnDNPv0jYaztyep9Tn06xXfuO1c254OmurbpVk6gd0MUWVVCXVEhQuF77djrpAwA\nve4/x752MwKBgDFtl4KxjPw4KkRrUXyXphBCURDNb6HM6DeYB0LwzvDyZ+7cYcIh\nO6Qg1Z68AyDSiYl8yB+PzDsWOZa49h2mi0CoeWXuEowHd8Xgzc8Ki1CowvfsE9IX\n0CgqzIfClgs6RlQpi7CmVnkZte+YMug8anipHJD+R/5qeNApwBEeXh9ZAoGBAJVy\niM/zJMidl9Tm7iuIHfsvNOTL9nPDcOTwUiBHD6i8ET7ZSepmKdmIusRygGkpXiS8\nyJes+nvRkSs5rfWeHptA1eoXKj+cIpA/Asql5e5oiPAGrEIbgnZTL2oSWJCdi/P3\nIGVF7Y2KeMYaUhrxIfEk93zBF3V7mFe13nMHTFjtAoGAB8CJ94WNKGWOBd9BtQ+k\nTlr/1+FRWqvzURVsyOphQJSWwMKPxwT+TG0WTO0d3RtGhkVmkDqCxRNmSmrstUFU\nQE80YttvcJJBZudl9hg12VSZBDygOo33thfVm/9vZsrsX16ElKDDQdLo98szNpcA\n2BjMOTnFCtsK85pAJV/zvjI=\n-----END PRIVATE KEY-----\n",
          "client_email": "gs-stellar-core-history-pusher@bloom-general.iam.gserviceaccount.com",
          "client_id": "104250768963248209738",
          "auth_uri": "https://accounts.google.com/o/oauth2/auth",
          "token_uri": "https://accounts.google.com/o/oauth2/token",
          "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
          "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/gs-stellar-core-history-pusher%40bloom-general.iam.gserviceaccount.com"
        }
  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: core
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: pazz
volumes:
  postgres:
